[package]
name = "uniblock"
version = "0.1.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]

[dependencies]
failure = "^0.1.1"
failure_derive = "^0.1.1"
reqwest = "^0.9.14"
regex = "^1.1.5"
lazy_static = "^1.3.0"
