[package]
name = "uniblock"
version = "0.1.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
edition = "2018"

[dependencies]
regex = "^1.1.5"
lazy_static = "^1.3.0"
surf = "^1.0.3"
async-std = "^1.6.3"
